apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "pia-dvh-import"
  namespace: "pia"
  labels:
    "team": "pia"
spec:
  image: {{image}}
  resources:
    requests:
      cpu: 100m
    limits:
      memory: 4096Mi
      cpu: 1000m
  kafka:
    pool: {{kafkaPool}}
  prometheus:
    enabled: true
    path: /metrics
  env:
    - name: GCS_SYKEFRAVARSSTATISTIKK_BUCKET_NAME  # GCS: Google Cloud Storage
      value: {{bucketName}}
    - name: GCS_URL
      value: "https://storage.googleapis.com"
