apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "pia-dvh-import"
  namespace: "pia"
  labels:
    "team": "pia"
spec:
  image: {{image}}
  resources:
    requests:
      memory: 1Gi
    limits:
      memory: 4Gi
  kafka:
    pool: {{kafkaPool}}
  prometheus:
    enabled: true
    path: /metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
    logging:
      destinations:
        - id: loki
        - id: elastic
  env:
    - name: GCS_SYKEFRAVARSSTATISTIKK_BUCKET_NAME  # GCS: Google Cloud Storage
      value: {{bucketName}}
    - name: GCS_URL
      value: "https://storage.googleapis.com"
