apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: kvartalsvis-sykefravarsstatistikk-virksomhet-v1
  namespace: pia
  labels:
    team: pia
spec:
  pool: {{kafkaPool}}
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: compact  # delete, compact, compact,delete
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: {{retentionHours}}  # avhengig av miljø
  acl:
    - team: pia
      application: pia-dvh-import
      access: readwrite   # read, write, readwrite
    - team: arbeidsgiver
      application: sykefravarsstatistikk-api
      access: read
    - team: pia
      application: pia-devops
      access: read
